/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hnb_PlayGame */

#ifndef _Included_com_example_hnb_PlayGame
#define _Included_com_example_hnb_PlayGame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hnb_PlayGame
 * Method:    movXY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_hnb_PlayGame_movXY
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hnb_PlayGame
 * Method:    printFND
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_hnb_PlayGame_printFND
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_hnb_PlayGame
 * Method:    printDOT
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_hnb_PlayGame_printDOT
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
